---

- hosts: all
  become: true
  tasks:
  - name: install apache2  and php package for Ubuntu 
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest  
      update_cache: yes  
    when: ansible_distribtuion == "Ubuntu"

      name: install httpd and php package for apache 
        - httpd
        - php
      state: latest
      update_cache: yes    
    when: ansible_distribtuion == "CentOS"    


